name: mvnw-deploy
on:
  workflow_dispatch:

jobs:
  mvnw-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - run: ./mvnw deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
