name: mvnw-test

on:
  pull_request:
    branches: [master]

jobs:
  mvnw-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: ./mvnw test
